# Generated by Django 5.0.6 on 2024-07-01 04:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='company_description',
        ),
        migrations.AddField(
            model_name='course',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='text', verbose_name='Text'),
        ),
    ]
