# Generated by Django 5.0.6 on 2024-07-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_alter_instructor_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='instructor',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
