# Generated by Django 5.0.6 on 2024-07-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_remove_instructor_social_media_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Language',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
