# Generated by Django 5.0.6 on 2024-07-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0012_auto_20240705_0533'),
    ]

    operations = [
    ]
