# Generated by Django 5.0.6 on 2024-07-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0019_rename_instructors_course_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.instructor'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='Courses.section'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
