# Generated by Django 5.0.6 on 2024-07-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0023_alter_applied_applicant_alter_applied_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='section',
        ),
        migrations.RemoveField(
            model_name='review',
            name='course',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.DeleteModel(
            name='Applied',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
