# Generated by Django 5.0.6 on 2024-07-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0024_remove_lecture_section_remove_review_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='user',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Courses.instructor'),
        ),
    ]
