# Generated by Django 5.0.6 on 2024-07-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0027_alter_instructor_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='teacher',
        ),
    ]
