# Generated by Django 5.0.6 on 2024-07-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0035_lesson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Section',
        ),
    ]
