# Generated by Django 5.0.6 on 2024-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0038_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
