# Generated by Django 5.0.6 on 2024-07-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('Instructor', 'Instructor')], max_length=14),
        ),
    ]
